apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2019-12-10T00:30:50Z
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "32"
    selfLink: /api/v1/namespaces/default/services/kubernetes
    uid: 517717dc-1ae4-11ea-82a6-0242ac11001d
  spec:
    clusterIP: 10.96.0.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"run":"wordpress"},"name":"wordpress","namespace":"default"},"spec":{"ports":[{"nodePort":31004,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"run":"wordpress"},"type":"NodePort"}}
    creationTimestamp: 2019-12-10T01:15:59Z
    labels:
      run: wordpress
    name: wordpress
    namespace: default
    resourceVersion: "4090"
    selfLink: /api/v1/namespaces/default/services/wordpress
    uid: 9fe77e48-1aea-11ea-82a6-0242ac11001d
  spec:
    clusterIP: 10.108.27.7
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 31004
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      run: wordpress
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2019-12-10T01:00:15Z
    labels:
      run: mysql
    name: wordpress-mysql
    namespace: default
    resourceVersion: "2826"
    selfLink: /api/v1/namespaces/default/services/wordpress-mysql
    uid: 6d0940ec-1ae8-11ea-82a6-0242ac11001d
  spec:
    clusterIP: 10.104.122.229
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      run: mysql
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
