apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"mysql-persistent-storage","namespace":""},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"1Gi"},"nfs":{"path":"/mysql","server":"nfs01"},"volumeMode":"Filesystem"}}
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: 2019-12-10T00:52:52Z
    finalizers:
    - kubernetes.io/pv-protection
    name: mysql-persistent-storage
    namespace: ""
    resourceVersion: "2208"
    selfLink: /api/v1/persistentvolumes/mysql-persistent-storage
    uid: 65710cb8-1ae7-11ea-82a6-0242ac11001d
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 1Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: mysql-persistent-storage
      namespace: default
      resourceVersion: "2206"
      uid: 69114632-1ae7-11ea-82a6-0242ac11001d
    nfs:
      path: /mysql
      server: nfs01
    persistentVolumeReclaimPolicy: Retain
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"wordpress-persistent-storage","namespace":""},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"1Gi"},"nfs":{"path":"/html","server":"nfs01"},"volumeMode":"Filesystem"}}
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: 2019-12-10T00:50:56Z
    finalizers:
    - kubernetes.io/pv-protection
    name: wordpress-persistent-storage
    namespace: ""
    resourceVersion: "2046"
    selfLink: /api/v1/persistentvolumes/wordpress-persistent-storage
    uid: 1fcaecbf-1ae7-11ea-82a6-0242ac11001d
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 1Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: wordpress-persistent-storage
      namespace: default
      resourceVersion: "2044"
      uid: 22d217b9-1ae7-11ea-82a6-0242ac11001d
    nfs:
      path: /html
      server: nfs01
    persistentVolumeReclaimPolicy: Retain
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
